- hosts: all
  become: yes
  user: ubuntu 
  gather_facts: no
  pre_tasks:
  - name: atualuzando 
    raw: 'apt-get update && sudo apt-get upgrade -y'
  - name: 'instalando o python'
    raw: 'apt-get -y install python'
  roles:
    - install-k8s

- hosts: k8s-master
  become: yes
  user: ubuntu 
  roles:
    - create-cluster
 
- hosts: k8s-workers
  become: yes
  user: ubuntu
  roles:
    - join-workers

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles:
    - install-helm
