apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-az
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.ip.odhserver.com/nginx-samu
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
